[ env ]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[font.normal]
family = "MesloLGS NF"

[scrolling]
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history= 10000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier= 3

[keyboard]
bindings = [
	{key = "c", mods = "Alt", chars="\u001Bc" },
	{key = "Left", mods = "Alt", chars="\u001Bb" },
	{key = "Right", mods = "Alt", chars="\u001Bf" },
  	{ key = "ArrowLeft", mods = "Command", chars = "\u001bOH" },  # Start of line
  	{ key = "ArrowRight", mods = "Command", chars = "\u001bOF" }, # End of line 
  	{ key = "Backspace", mods = "Command", chars = "\u0015" },    # Delete line
	{ key="ArrowUp", mods="Control|Shift", action="ScrollLineUp" },
    { key="ArrowDown", mods="Control|Shift", action="ScrollLineDown" }
]

